<a href="https://colab.research.google.com/github/Thomas-D40/data-course/blob/main/Analyse_de_donn%C3%A9es_avec_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from google.colab import drive
drive.mount('/gdrive')

url = '/gdrive/MyDrive/python-data-course'
filename = 'world_alcohol.csv'

world_alcohol = np.genfromtxt(url + '/' + filename, delimiter=',', dtype='U75', skip_header=1)
world_alcohol

Mounted at /gdrive


array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

# Effectuer des comparaisons

In [2]:
vector = np.array([5,10,15,20])

vector == 10 # Ceci permet de comparer chaque valeur du tableau pour obtenir un nouveau vecteur de booléen

array([False,  True, False, False])

In [65]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix = matrix + 1 # L'addition s'applique également sur toutes les valeurs
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Exercice:
- Extraire la 3ème colonne de world_alcohol et comparer la à Canada et assigner à countries_canada
- Extraitre la première colonne et comparer à 1984 et assigner à years_1984

In [4]:
countries_canada = world_alcohol[:,2] == "Canada"
years_1984 = world_alcohol[:, 0] == 1984

print(countries_canada)
print(years_1984)

[False False False ... False False False]
[False False False ... False False False]


# Sélectionner des éléments

In [5]:
vector = np.array([5,10,15,20])

equal_to_ten = (vector == 10)
print(equal_to_ten) # Génère le vecteur de booléan
print(vector[equal_to_ten]) # A partir de vector et du vecteur de boolean, génère un vecteur des valeurs si le boolean est à true

[False  True False False]
[10]


In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

second_colomn_5 = (matrix[:,1] == 5)
print(second_colomn_5)
print(matrix[second_colomn_5, :]) # Donne la ligne où il y a un true
print(matrix[second_colomn_5, 1])



[False  True False]
[[4 5 6]]
[5]


Exercice:
- Comparer 3ème colonne à Algeria et assigner à country_is_algeria
- Selections seulements les lignes de wolrd_alcohol pour les quelques country_is_algeria vaut True
- Assigner le résultat à country_algeria


Même travail pour 1984

In [7]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [8]:
country_is_algeria = world_alcohol[:, 2] == "Algeria"
country_algeria = world_alcohol[country_is_algeria, :]
print(country_algeria)
print(country_algeria.shape)

year_is_1984 = world_alcohol[:, 0] == "1984"
year_1984 = world_alcohol[year_is_1984, :]
print(year_1984)
print(year_1984.shape)


[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]
(20, 5)
[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa

# Effectuer des comparaisons avec plusieurs conditions avec AND & OR

In [9]:
vector = np.array([5,10,15,20])

equal_to_ten_and_five = (vector == 10) & (vector == 5)
equal_to_ten_and_five

equal_to_ten_or_five = (vector == 10) | (vector == 5)
equal_to_ten_or_five

array([ True,  True, False, False])

Exercice:
- Créer double comparaison et assigner à is_algeria_and_1986
- Créer la varialbe rows_with_algeria_and_1986

In [10]:
is_algeria_and_1986 = (world_alcohol[:, 2] == "Algeria") & (world_alcohol[:, 0] == "1986")
is_algeria_and_1986

rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986, :]
rows_with_algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

# Remplacer des valeurs par un tableau NumPy

In [11]:
vector = np.array([5,10,15,20])

equal_to_ten_or_five = (vector == 10) | (vector == 5)

vector[equal_to_ten_or_five] = 50

vector

array([50, 50, 15, 20])

In [12]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

second_column_5 = matrix[:, 1] == 5

matrix[second_colomn_5, 1] = 15

matrix

array([[ 1,  2,  3],
       [ 4, 15,  6],
       [ 7,  8,  9]])

Exercice:
- Créer un tableau numpy world_alcohol_2 égal à world_alcohol pour le dupliquer sous un autre nom
- Remplacer toutes les années 1986 par "2018
- Remplacer tous les alccols "Wine par "Beer"

In [13]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [14]:
world_alcohol_2 = world_alcohol

is_1986 = world_alcohol_2[:, 0] == "1986"
is_wine = world_alcohol_2[:, 3] == "Wine"

world_alcohol_2[is_1986, 0] = "2018"
world_alcohol_2[is_wine, 3] = "Beer"

print(world_alcohol_2)
print(world_alcohol_2[world_alcohol_2[:, 0] == "2018"])

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]
[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['2018' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['2018' 'Western Pacific' 'Fiji' 'Spirits' '0.05']
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


# Remplacer chaines de caractères vides

Comparer tous les éléments de la 5ème colonne à la chaine de caractères vides, assigner ce résultat à is_value_empty

Remplacer les '' par des 0

In [16]:
is_value_empty = world_alcohol[:, 4] == ''

world_alcohol[is_value_empty, 4] = '0'

world_alcohol

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

# Convertir les types de données

In [17]:
# astype()

vector = np.array(["1","2","3"])

vector = vector.astype(float)

vector

array([1., 2., 3.])

Extraire 5ème colonne de world_alcohol as alcohol_consumption + conversion en flaot

In [19]:
alcohol_consumption = world_alcohol[:, 4]

alcohol_consumption = alcohol_consumption.astype(float)

alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

# Calculs mathématiques avec NumPy

- sum()
- mean()
- max()

S'applique à chaque fois sur les valeurs d'un vecteur ou d'une dimension d'une matrice (soit colonne, soit ligne)

In [22]:
vector = np.array([5,10,15,20])

vector.sum() # 50

vector.mean() # 12.5

vector.max() # 20

20

In [25]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.sum(axis=1) # Somme des lignes
matrix.sum(axis=0) # Somme des colonnes
matrix.sum() # Somme toutes les valeurs

45

Exercice:

Utiliser sum() pour calculer la somme des valeurs d'alcool dans total_alcohol, puis mean pour average_alcohol

In [27]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()

print(total_alcohol, average_alcohol)

3908.96 1.2001719373656738


# Calculer consommation totale annuelle par habitant pour un pays donné

In [29]:
world_alcohol[world_alcohol[:, 2] == "France"]

array([['1985', 'Europe', 'France', 'Spirits', '2.7'],
       ['1989', 'Europe', 'France', 'Beer', '10.24'],
       ['2018', 'Europe', 'France', 'Other', '0.25'],
       ['1989', 'Europe', 'France', 'Other', '0.27'],
       ['1984', 'Europe', 'France', 'Spirits', '2.58'],
       ['1987', 'Europe', 'France', 'Beer', '2.45'],
       ['2018', 'Europe', 'France', 'Spirits', '2.71'],
       ['1989', 'Europe', 'France', 'Beer', '2.56'],
       ['2018', 'Europe', 'France', 'Beer', '2.55'],
       ['1984', 'Europe', 'France', 'Beer', '2.62'],
       ['1984', 'Europe', 'France', 'Other', '0.24'],
       ['1985', 'Europe', 'France', 'Beer', '11.1'],
       ['1985', 'Europe', 'France', 'Other', '0.25'],
       ['2018', 'Europe', 'France', 'Beer', '10.62'],
       ['1989', 'Europe', 'France', 'Spirits', '2.98'],
       ['1985', 'Europe', 'France', 'Beer', '2.54'],
       ['1987', 'Europe', 'France', 'Beer', '10.42'],
       ['1984', 'Europe', 'France', 'Beer', '11.45'],
       ['1987', 'Europe', '

Exercice:
Créer une matrice canada_1986
Extraire 5ème colonne et remplacer '' par '0' puis convertir en float, assigner le résultat à canada_alcohol
Calculer somme dans total_canadian_driking

In [50]:
canada_2018 = world_alcohol[(world_alcohol[:, 2] == "Canada")  & (world_alcohol[:, 0] == "2018")] # Absence de données en 1986

is_value_empty = canada_2018[:, 4] == ''
canada_2018[(canada_2018[:, 4] == ''), 4] = '0'
print(canada_2018)

canada_alcohol = canada_2018[:,4].astype(float)
print(canada_alcohol)

total_canadian_driking = canada_alcohol.sum()

print(total_canadian_driking)


[['2018' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Spirits' '3.11']
 ['2018' 'Americas' 'Canada' 'Beer' '4.87']
 ['2018' 'Americas' 'Canada' 'Beer' '1.33']]
[0.   3.11 4.87 1.33]
9.31


Exercice:
Créer dictionnaire vide: pays / consommations associés => totals

Sélectionner les lignes de world_alochol correspond à 1989 => year

Sélectionner dans une liste countries

Parcourir les pays via une boucle:

- Sélectionner les lignes de year pour le pays
- Assigner résultat à country_consumption
- Extraire 5ème colonne
- Remplacer par 0
- Convertir en float
- Calculer somme
- Ajouter au dictionnaire

Afficher le dictionnaire


In [59]:
# Calcul pour chaque pays


totals = {}

year = world_alcohol[world_alcohol[:,0] == "1989", :]
print(year)
countries = []
for country in year[:, 2]:
  if country not in countries:
    countries.append(country)

print(countries)

countries_v2 = world_alcohol[:, 2]
print(countries_v2)

test = np.array(["Toto","Toto","Toto",1])
print(test)

for country in countries:
  country_consumption = year[year[:, 2] == country]
  country_consumption[(country_consumption[:, 4] == ''), 4] = '0'
  country_consumption = country_consumption[:, 4].astype(float)
  totals[country] = country_consumption.sum()

print(totals)
# for country in countries:
#   country_consumption = year[]

[['1989' 'Americas' 'Guatemala' 'Beer' '0.62']
 ['1989' 'Africa' 'Seychelles' 'Beer' '2.23']
 ['1989' 'Americas' 'Costa Rica' 'Spirits' '4.51']
 ...
 ['1989' 'Eastern Mediterranean' 'Morocco' 'Spirits' '0.07']
 ['1989' 'Europe' 'Poland' 'Beer' '2.03']
 ['1989' 'Europe' 'Turkey' 'Other' '0']]
['Guatemala', 'Seychelles', 'Costa Rica', 'Mauritius', 'Zimbabwe', 'Suriname', 'Croatia', 'Syrian Arab Republic', 'Bolivia (Plurinational State of)', 'Somalia', 'Namibia', 'Uganda', 'Afghanistan', 'Jamaica', 'Finland', 'Iraq', 'Malawi', 'Bulgaria', 'Nicaragua', 'Central African Republic', 'Burundi', 'Sweden', 'Greece', 'Kyrgyzstan', 'Belgium', 'Angola', 'Burkina Faso', 'Czech Republic', 'United Arab Emirates', 'Peru', 'Trinidad and Tobago', 'Guyana', 'Bahrain', 'Benin', 'Liberia', 'Viet Nam', 'Belarus', 'Swaziland', 'France', 'United States of America', 'Cabo Verde', 'Saudi Arabia', 'Poland', 'Senegal', 'Slovenia', 'Hungary', 'Iran (Islamic Republic of)', 'Lesotho', 'Gabon', 'Comoros', 'Italy', 'De

# Trouver le pays qui consomme le plus

Créer une variable highest_value qu'on initie à 0

Créer une variable hight_key qui gardera en mémoire le nom du pays associé, on la fixe à None

Parcourir totals et afficher le pays qui consomme le plus

In [62]:
highest_value = 0
highest_key = None

# for key, value in totals.items():
#   if value > highest_value:
#     highest_value = value
#     highest_key= key

# Alternative
for country in totals:
  if totals[country] > highest_value:
    highest_value = totals[country]
    highest_key = country

print(highest_key, highest_value)

Hungary 16.29
