<a href="https://colab.research.google.com/github/Thomas-D40/data-course/blob/main/D%C3%A9couverte_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction Numpy

Avantage des listes pythons:
- peuvent contenir différents types de données
- peuvent rétrécir et grandir dynamique


Inconvénients:
- consomment beaucoup d'énerges
- problématiques pour des datasets de moyenne à très grande taille

# Les tableaux de Numpy

ndarray => tableau numpy de n dimensions

Rappel:
un tableau de dimension 1 est un vecteur.

un tableau de dimension x (x > 1) est une matrice

In [2]:
import numpy as np

vector = np.array([3,4,17,65])
vector

array([ 3,  4, 17, 65])

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice:

1 - Créer un vecteur depuis la liste [10,20,30] et l'assigner à la variable vector

2 - Créer une matrice depuis la liste [[5,10,15],[20,25,30],[35,40,45]] et l'assigner à la variable matrix

In [6]:
vector = np.array([10,20,30])
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

vector, matrix

(array([10, 20, 30]),
 array([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]))

# Taille d'un tableau

In [7]:
vector = np.array(['1986', 'Western Pacifi', 'Viet Nam', 'Wine', 0])

array(['1986', 'Western Pacifi', 'Viet Nam', 'Wine', '0'], dtype='<U21')

In [10]:
matrix = np.array([[5,10,15],[20,25,30]])

In [11]:
vector.shape, matrix.shape

((3,), (2, 3))

# Lire un dataset

Fonction: numpy.genfromtxt()

In [33]:
import numpy as np
from google.colab import drive
drive.mount('/gdrive')

url = '/gdrive/MyDrive/python-data-course'
filename = 'world_alcohol.csv'

world_alcohol = np.genfromtxt(url + '/' + filename, delimiter=',')
print(type(world_alcohol))
print(world_alcohol)

<class 'numpy.ndarray'>
[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.986e+03       nan       nan       nan 2.540e+00]
 [1.987e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.150e+00]]


Sans précision du type, Numpy a défini que le type correct des données était float64 et a converti tout ce qui n'est pas un nombre en NaN

# Les types de données Numpy


- bool => True or False
- int => avec des sous-types int16, int32 ou int64
- float => comme ci-dessus
- string

- nan => Not a Number
- na => Not Available


La particularité d'un tableau Numpy est que toutes les données d'un tableau sont du même type.

Ce type peut être obtenu avec la méthode Numpy **dtype**

In [28]:
numbers = np.array([1,2,3])
numbers.dtype

dtype('int64')

In [35]:
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

float64


# Afficher correctement les données

In [41]:
world_alcohol = np.genfromtxt(url + '/' + filename, delimiter=',',
                              dtype = "U75",  # Unicode 75 Bits
                              skip_header = True
                              )
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

# Extraire une valeur depuis un tableau Numpy

In [42]:
vector = np.array([1,2,5])

print(vector[0])

1


In [47]:
matrix = np.array([[0,1,2],[3,4,5]])
print(matrix[0][1]) # Approche naïve

first_row = matrix[0]
print(first_row)

print(matrix[0,1]) # Première valeur : ligne, seconde valeur: colonne

1
[0 1 2]
1


Exercice: Extraire une valeur depuis un tableau Numpy

- Assigner le nombre de litres de vin bu par un Ivoirien en 1985 à la variable ivoire_1985 (troisième ligne)
- Assiner le nom du pays de la 2ème ligne à la variable second_country

In [48]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [50]:
ivoire_1985 = world_alcohol[2,4]
second_country = world_alcohol[1,2]

ivoire_1985, second_country

('1.62', 'Uruguay')

# Extraire un vecteur de valeurs depuis un tableau  NumPy

In [51]:
vector = np.array([5,10,15,20])

In [55]:
vector[0:3]

array([ 5, 10, 15])

In [62]:
matrix = np.array([[0,1,2],[3,4,5]])

print(matrix)

print(matrix[1,:2]) # Les valeurs des index 0 jusqu'à 3 exclus de la ligne 2
print(matrix[:,1]) # Toutes les valeurs de la colonne 1
print(matrix[:, :2])

[[0 1 2]
 [3 4 5]]
[3 4]
[1 4]
[[0 1]
 [3 4]]


Exercice
- Assigner toute la 3e colonne de world_alcohol à la variable countries
- Assigner l'ensemble de la 5e colonne à la variable alcohol_consumption

In [64]:
countries = world_alcohol[:,2]
alcohol_consumption = world_alcohol[:, 4]

countries, alcohol_consumption

(array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
        'Papua New Guinea', 'Swaziland'], dtype='<U75'),
 array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75'))

# Extraire un tableau de valeurs depuis un tableau Numpy

In [65]:
matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [68]:
matrix[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [69]:
matrix[1:3,0:2]

array([[3, 4],
       [6, 7]])

Exercice:
- Assigner toutes les lignes des deux premières colonnes à la variable first_two_columns
- Assigner les 10 premières lignes de la colonne à la variable first_ten_years
- Assigner les 10 premères lignes de toutes les colonnes à first_ten_rows
- Assigner 20 premières lignes des colonnes d'indice 1 et 2 à first_twenty-regions

In [70]:
first_two_columns = world_alcohol[:,:2]
first_ten_years = world_alcohol[:10,0]
first_ten_rows = world_alcohol[:10,:]
first_twenty_regions = world_alcohol[:20,1:3]

first_two_columns, first_ten_years, first_ten_rows, first_twenty_regions

(array([['1986', 'Western Pacific'],
        ['1986', 'Americas'],
        ['1985', 'Africa'],
        ...,
        ['1986', 'Europe'],
        ['1987', 'Western Pacific'],
        ['1986', 'Africa']], dtype='<U75'),
 array(['1986', '1986', '1985', '1986', '1987', '1987', '1987', '1985',
        '1986', '1984'], dtype='<U75'),
 array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
        ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
        ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
        ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
        ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
        ['1987', 'Americas', 'Guatemala', 'Other', '0'],
        ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
        ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
        ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
        ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75'),
 array([['Western Pacific', 'Viet Nam'],
        